language: php

sudo: false

php:
  - 7.1
  - 7.2

before_install:
  - composer self-update

install:
  - composer update

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
